<?php 
include  '../../ex_common/query.php'; 
$respuesta = array();
$respuesta=$database->query(
	"(SELECT A.ASUNTO,A.FECHA_INICIO, A.FECHA_FIN, A.ID_COTIZACION as ID_COTIZACION, B.NOMBRE, C.DESCRIPCION ,SUBSTRING(A.OBSERVACIONES, 1, 150) as OBSERVACIONES, A.ENTIDAD,
	COT.FOLIO_CONSECUTIVO, COT.FOLIO_INICIALES, COT.FOLIO_UPDATE, COT.FOLIO_SERVICIO, COT.FOLIO_MES, COT.FOLIO_YEAR
FROM PROSPECTO_CITAS A 
INNER JOIN PROSPECTO B ON A.ID_PROSPECTO = B.ID 
INNER JOIN TIPO_ASUNTO C ON C.ID = A.TIPO_ASUNTO
LEFT JOIN COTIZACIONES COT ON COT.ID = A.ID_COTIZACION
WHERE A.ENTIDAD = 1)
UNION
(SELECT A.ASUNTO,A.FECHA_INICIO, A.FECHA_FIN, A.ID_COTIZACION as ID_COTIZACION, B.NOMBRE, C.DESCRIPCION ,SUBSTRING(A.OBSERVACIONES, 1, 150) as OBSERVACIONES, A.ENTIDAD ,
	COT.FOLIO_CONSECUTIVO, COT.FOLIO_INICIALES, COT.FOLIO_UPDATE, COT.FOLIO_SERVICIO, COT.FOLIO_MES, COT.FOLIO_YEAR
FROM PROSPECTO_CITAS A 
INNER JOIN CLIENTES B ON A.ID_PROSPECTO = B.ID 
INNER JOIN TIPO_ASUNTO C ON C.ID = A.TIPO_ASUNTO
LEFT JOIN COTIZACIONES COT ON COT.ID = A.ID_COTIZACION
WHERE A.ENTIDAD = 2)
")->fetchAll(PDO::FETCH_ASSOC);

for ($i=0; $i < count($respuesta); $i++) { 
	$CONSECUTIVO = str_pad("".$respuesta[$i]["FOLIO_CONSECUTIVO"], 5, "0", STR_PAD_LEFT);
	$FOLIO = $respuesta[$i]["FOLIO_INICIALES"].$respuesta[$i]["FOLIO_SERVICIO"].$CONSECUTIVO.$respuesta[$i]["FOLIO_MES"].$respuesta[$i]["FOLIO_YEAR"];
	if( !is_null($respuesta[$i]["FOLIO_UPDATE"]) && $respuesta[$i]["FOLIO_UPDATE"] != ""){
		$FOLIO .= "-".$respuesta[$i]["FOLIO_UPDATE"];
	}
	$respuesta[$i]["FOLIO"] = $FOLIO;
}
	valida_error_medoo_and_die("PROSPECTO_CITAS", "jungik.choi@dhttecno.com");
	print_r(json_encode($respuesta));  
 ?>