<?php 
include  '../../ex_common/query.php';

$consulta = "SELECT P.NOMBRE,PD.ESTADO,PC.NOMBRE AS NOMBRE_CONTACTO,PC.PUESTO,PC.TELEFONO,PC.CORREO,PC.CELULAR
FROM PROSPECTO P 
INNER JOIN PROSPECTO_CONTACTO PC
ON P.ID = PC.ID_PROSPECTO
LEFT JOIN PROSPECTO_DOMICILIO PD
ON PC.ID_PROSPECTO_DOMICILIO = PD.ID
WHERE P.ID = ".$_REQUEST["id"];
/*
."
GROUP BY P.NOMBRE,PD.ESTADO,PC.NOMBRE,PC.PUESTO,PC.TELEFONO,PC.CORREO,PC.CELULAR"; 
*/
$resultado = $database->query($consulta)->fetchAll();
	print_r(json_encode($resultado)); 
