<?php
	include  '../../ex_common/query.php'; 
	
	$nombre_tabla = "PROSPECTO_PRODUCTO";
	$correo = "leovardo.quintero@dhttecno.com";
	
	$id_prospecto = $_REQUEST["id"]; 
	$prospecto_producto = $database->query("SELECT 
    SERVICIOS.NOMBRE AS NOMBRE_SERVICIO, 
    SERVICIOS.ID AS ID_SERVICIO,
    TIPOS_SERVICIO.ID AS ID_TIPO_SERVICIO,
    TIPOS_SERVICIO.NOMBRE AS NOMBRE_TIPO_SERVICIO,
    NORMAS.ID AS ID_NORMA,
    NORMAS.NOMBRE AS NOMBRE_NORMA,
    PROSPECTO_PRODUCTO.ID_PROSPECTO AS ID_PROSPECTO,
    PROSPECTO_PRODUCTO.ALCANCE AS ALCANCE
    FROM 
    PROSPECTO_PRODUCTO 
    LEFT JOIN SERVICIOS 
    ON PROSPECTO_PRODUCTO.ID_SERVICIO = SERVICIOS.ID
    LEFT JOIN TIPOS_SERVICIO
    ON PROSPECTO_PRODUCTO.ID_TIPO_SERVICIO = TIPOS_SERVICIO.ID
    LEFT JOIN NORMAS
    ON PROSPECTO_PRODUCTO.ID_NORMA = NORMAS.ID
    WHERE
    PROSPECTO_PRODUCTO.ID_PROSPECTO = ".$id_prospecto)->fetchAll(PDO::FETCH_ASSOC);

	valida_error_medoo_and_die($nombre_tabla ,$correo ); 
	print_r(json_encode($prospecto_producto)); 
?> 
