<?php 
// error_reporting(E_ALL);
// ini_set("display_errors",1);

include  '../../common/conn-apiserver.php'; 
include  '../../common/conn-medoo.php'; 
include  '../../common/conn-sendgrid.php'; 

function valida_parametro_and_die($parametro, $mensaje_error){
	$parametro = "".$parametro;
	if ($parametro == "") {
		$respuesta['resultado'] = 'error';
		$respuesta['mensaje'] = $mensaje_error;
		print_r(json_encode($respuesta));
		die();
	}
}

function valida_error_medoo_and_die(){
	global $database, $mailerror;
	if ($database->error()[2]) { //Aqui está el error
		$respuesta['resultado']="error";
		$respuesta['mensaje']="Error al ejecutar script: " . $database->error()[2];
		print_r(json_encode($respuesta));
		$mailerror->send("certificando", getcwd(), $database->error()[2], $database->last_query(), "polo@codeart.mx");
		die();
	}
}

$respuesta=array();
$json = file_get_contents('php://input'); //Obtiene lo que se envía vía POST
$objeto = json_decode($json); // Lo transforma de JSON a un objeto de PHP

$NOMBRE = $objeto->NOMBRE;
$NOMBRE_CONTAINS = $objeto->NOMBRE_CONTAINS; // contains = 1, starts with = 0

$APELLIDO_MATERNO = $objeto->APELLIDO_MATERNO;
$APELLIDO_MATERNO_CONTAINS = $objeto->APELLIDO_MATERNO_CONTAINS; // contains = 1, starts with = 0

$APELLIDO_PATERNO = $objeto->APELLIDO_PATERNO;
$APELLIDO_PATERNO_CONTAINS = $objeto->APELLIDO_PATERNO_CONTAINS; // contains = 1, starts with = 0

$ENTIDAD_FEDERATIVA = $objeto->ENTIDAD_FEDERATIVA;
$ENTIDAD_FEDERATIVA_CONTAINS = $objeto->ENTIDAD_FEDERATIVA_CONTAINS; // contains = 1, starts with = 0

$REGISTRO_CALIFICACION = $objeto->REGISTRO_CALIFICACION;
$REGISTRO_CALIFICACION_CONTAINS = $objeto->REGISTRO_CALIFICACION_CONTAINS; // contains = 1, starts with = 0

$CLAVE_SECTOR = $objeto->CLAVE_SECTOR;

$NOMBRE_SECTOR = $objeto->NOMBRE_SECTOR;
$NOMBRE_SECTOR_CONTAINS = $objeto->NOMBRE_SECTOR_CONTAINS; // contains = 1, starts with = 0

$CLAVE_TIPO_SERVICIO = $objeto->CLAVE_TIPO_SERVICIO;

$NOMBRE_TIPO_SERVICIO = $objeto->NOMBRE_TIPO_SERVICIO;
$NOMBRE_TIPO_SERVICIO_CONTAINS = $objeto->NOMBRE_TIPO_SERVICIO_CONTAINS; // contains = 1, starts with = 0

$ACTIVOS = $objeto->ACTIVO;
$whereACTIVOS = "";
if ($ACTIVOS != "TODOS") {
	$whereACTIVOS = " AND PERSONAL_TECNICO.STATUS = " . $database->quote($ACTIVOS);
}


$fromPERSONAL_TECNICO_CALIFICACIONES = "";
$fromPERSONAL_TECNICO_CALIF_SECTOR = "";
$fromPERSONAL_TECNICO_DOMICILIOS = "";
$fromSECTORES = "";
$fromTIPOS_SERVICIO = "";

$wherePERSONAL_TECNICO_CALIFICACIONES = "";
$wherePERSONAL_TECNICO_CALIF_SECTOR = "";
$wherePERSONAL_TECNICO_DOMICILIOS = "";
$whereSECTORES = "";
$whereTIPOS_SERVICIO = "";

$whereNOMBRE = "";
if ($NOMBRE != "") {
	$likeNOMBRE = "";
	if ($NOMBRE_CONTAINS) {
		$likeNOMBRE = "%";
	}
	$whereNOMBRE = " AND PERSONAL_TECNICO.NOMBRE LIKE " . $database->quote($likeNOMBRE.$NOMBRE."%");
}

$whereAPELLIDO_MATERNO = "";
if ($APELLIDO_MATERNO != "") {
	$likeAPELLIDO_MATERNO = "";
	if ($APELLIDO_MATERNO_CONTAINS) {
		$likeAPELLIDO_MATERNO = "%";
	}
	$whereAPELLIDO_MATERNO = " AND PERSONAL_TECNICO.APELLIDO_MATERNO LIKE " . $database->quote($likeAPELLIDO_MATERNO.$APELLIDO_MATERNO."%");
}

$whereAPELLIDO_PATERNO = "";
if ($APELLIDO_PATERNO != "") {
	$likeAPELLIDO_PATERNO = "";
	if ($APELLIDO_PATERNO_CONTAINS) {
		$likeAPELLIDO_PATERNO = "%";
	}
	$whereAPELLIDO_PATERNO = " AND PERSONAL_TECNICO.APELLIDO_PATERNO LIKE " . $database->quote($likeAPELLIDO_PATERNO.$APELLIDO_PATERNO."%");
}

$whereENTIDAD_FEDERATIVA = "";
if ($ENTIDAD_FEDERATIVA != "") {
	$likeENTIDAD_FEDERATIVA = "";
	if ($ENTIDAD_FEDERATIVA_CONTAINS) {
		$likeENTIDAD_FEDERATIVA = "%";
	}
	$whereENTIDAD_FEDERATIVA = " AND PERSONAL_TECNICO_DOMICILIOS.ENTIDAD_FEDERATIVA LIKE " . $database->quote($likeENTIDAD_FEDERATIVA.$ENTIDAD_FEDERATIVA."%");
	$fromPERSONAL_TECNICO_DOMICILIOS = ", PERSONAL_TECNICO_DOMICILIOS ";
	$wherePERSONAL_TECNICO_DOMICILIOS = " AND PERSONAL_TECNICO_DOMICILIOS.ID_PERSONAL_TECNICO = PERSONAL_TECNICO.ID ";
}

$whereREGISTRO_CALIFICACION = "";
if ($REGISTRO_CALIFICACION != "") {
	$likeREGISTRO_CALIFICACION = "";
	if ($REGISTRO_CALIFICACION_CONTAINS) {
		$likeREGISTRO_CALIFICACION = "%";
	}
	$whereREGISTRO_CALIFICACION = " AND PERSONAL_TECNICO_CALIFICACIONES.REGISTRO LIKE " . $database->quote($likeREGISTRO_CALIFICACION.$REGISTRO_CALIFICACION."%");
	$fromPERSONAL_TECNICO_CALIFICACIONES = ", PERSONAL_TECNICO_CALIFICACIONES ";
	$wherePERSONAL_TECNICO_CALIFICACIONES = " AND PERSONAL_TECNICO_CALIFICACIONES.ID_PERSONAL_TECNICO = PERSONAL_TECNICO.ID ";
}

$whereCLAVE_SECTOR = "";
if ($CLAVE_SECTOR != "TODOS") {
	$whereCLAVE_SECTOR = " AND SECTORES.ID = " . $database->quote($CLAVE_SECTOR);

	$fromPERSONAL_TECNICO_CALIFICACIONES = ", PERSONAL_TECNICO_CALIFICACIONES ";
	$wherePERSONAL_TECNICO_CALIFICACIONES = " AND PERSONAL_TECNICO_CALIFICACIONES.ID_PERSONAL_TECNICO = PERSONAL_TECNICO.ID ";

	$fromPERSONAL_TECNICO_CALIF_SECTOR = ", PERSONAL_TECNICO_CALIF_SECTOR ";
	$wherePERSONAL_TECNICO_CALIF_SECTOR = " AND PERSONAL_TECNICO_CALIF_SECTOR.ID_PERSONAL_TECNICO_CALIFICACION  = PERSONAL_TECNICO_CALIFICACIONES.ID ";

	$fromSECTORES = ", SECTORES ";
	$whereSECTORES = " AND SECTORES.ID_SECTOR  = PERSONAL_TECNICO_CALIF_SECTOR.ID_SECTOR  ";
}

$whereNOMBRE_SECTOR = "";
if ($NOMBRE_SECTOR != "") {
	$likeNOMBRE_SECTOR = "";
	if ($NOMBRE_SECTOR_CONTAINS) {
		$likeNOMBRE_SECTOR = "%";
	}
	$whereNOMBRE_SECTOR = " AND SECTORES.NOMBRE LIKE " . $database->quote($likeNOMBRE_SECTOR.$NOMBRE_SECTOR."%");

	$fromPERSONAL_TECNICO_CALIFICACIONES = ", PERSONAL_TECNICO_CALIFICACIONES ";
	$wherePERSONAL_TECNICO_CALIFICACIONES = " AND PERSONAL_TECNICO_CALIFICACIONES.ID_PERSONAL_TECNICO = PERSONAL_TECNICO.ID ";

	$fromPERSONAL_TECNICO_CALIF_SECTOR = ", PERSONAL_TECNICO_CALIF_SECTOR ";
	$wherePERSONAL_TECNICO_CALIF_SECTOR = " AND PERSONAL_TECNICO_CALIF_SECTOR.ID_PERSONAL_TECNICO_CALIFICACION  = PERSONAL_TECNICO_CALIFICACIONES.ID ";

	$fromSECTORES = ", SECTORES ";
	$whereSECTORES = " AND SECTORES.ID_SECTOR  = PERSONAL_TECNICO_CALIF_SECTOR.ID_SECTOR  ";
}

$whereCLAVE_TIPO_SERVICIO = "";
if ($CLAVE_TIPO_SERVICIO != "") {
	$whereCLAVE_TIPO_SERVICIO = " AND TIPOS_SERVICIO.ID = " . $database->quote($CLAVE_TIPO_SERVICIO);

	$fromPERSONAL_TECNICO_CALIFICACIONES = ", PERSONAL_TECNICO_CALIFICACIONES ";
	$wherePERSONAL_TECNICO_CALIFICACIONES = " AND PERSONAL_TECNICO_CALIFICACIONES.ID_PERSONAL_TECNICO = PERSONAL_TECNICO.ID ";

	$fromTIPOS_SERVICIO = ", TIPOS_SERVICIO ";
	$whereTIPOS_SERVICIO = " AND TIPOS_SERVICIO.ID  = PERSONAL_TECNICO_CALIFICACIONES.ID_TIPO_SERVICIO  ";
}

$whereNOMBRE_TIPO_SERVICIO = "";
if ($NOMBRE_TIPO_SERVICIO != "") {
	$likeNOMBRE_TIPO_SERVICIO = "";
	if ($NOMBRE_TIPO_SERVICIO_CONTAINS) {
		$likeNOMBRE_TIPO_SERVICIO = "%";
	}
	$whereNOMBRE_TIPO_SERVICIO = " AND TIPOS_SERVICIO.NOMBRE LIKE " . $database->quote($likeNOMBRE_TIPO_SERVICIO.$NOMBRE_TIPO_SERVICIO."%");

	$fromPERSONAL_TECNICO_CALIFICACIONES = ", PERSONAL_TECNICO_CALIFICACIONES ";
	$wherePERSONAL_TECNICO_CALIFICACIONES = " AND PERSONAL_TECNICO_CALIFICACIONES.ID_PERSONAL_TECNICO = PERSONAL_TECNICO.ID ";

	$fromTIPOS_SERVICIO = ", TIPOS_SERVICIO ";
	$whereTIPOS_SERVICIO = " AND TIPOS_SERVICIO.ID  = PERSONAL_TECNICO_CALIFICACIONES.ID_TIPO_SERVICIO  ";
}

$strQuery = "SELECT DISTINCT PERSONAL_TECNICO.ID, PERSONAL_TECNICO.NOMBRE, PERSONAL_TECNICO.APELLIDO_PATERNO,
      						PERSONAL_TECNICO.APELLIDO_MATERNO, PERSONAL_TECNICO.FECHA_NACIMIENTO, PERSONAL_TECNICO.CURP,
      						PERSONAL_TECNICO.RFC, PERSONAL_TECNICO.TELEFONO_FIJO, PERSONAL_TECNICO.TELEFONO_CELULAR,
      						PERSONAL_TECNICO.EMAIL, PERSONAL_TECNICO.STATUS, PERSONAL_TECNICO.IMAGEN_BASE64, PERSONAL_TECNICO.INICIALES 
			FROM PERSONAL_TECNICO " 
			. $fromPERSONAL_TECNICO_CALIFICACIONES . $fromPERSONAL_TECNICO_CALIF_SECTOR . $fromPERSONAL_TECNICO_DOMICILIOS . $fromSECTORES . $fromTIPOS_SERVICIO 
			. " WHERE 1 "

			 		. $wherePERSONAL_TECNICO_CALIFICACIONES . $wherePERSONAL_TECNICO_CALIF_SECTOR . $wherePERSONAL_TECNICO_DOMICILIOS . $whereSECTORES . $whereTIPOS_SERVICIO

     				. $whereNOMBRE . $whereAPELLIDO_MATERNO . $whereAPELLIDO_PATERNO . $whereENTIDAD_FEDERATIVA . $whereREGISTRO_CALIFICACION . $whereCLAVE_SECTOR . $whereNOMBRE_SECTOR . $whereCLAVE_TIPO_SERVICIO . $whereNOMBRE_TIPO_SERVICIO . $whereACTIVOS;

//print_r($strQuery);
// die();

$arreglo_personal_tecnico = $database->query($strQuery)->fetchAll();
valida_error_medoo_and_die();

//print_r($strQuery);
print_r(json_encode($arreglo_personal_tecnico));


//-------- FIN --------------
?>